### ISSUE TITLE
[TCE-1016] Support `match` statements

### ISSUE THREAD

**Issue by Kakadus** [codacy/codacy-prospector#231]
With python 3.10, python supports [Structural Pattern Matching](https://docs.python.org/3.10/reference/compound_stmts.html#match) via the `match` statement. As this plugin seems to be running on python 3.9 it is not supported. Thus, we see codacy errors with `SyntaxError: invalid syntax (E901)`. Please support python 3.10 and above.

**Comment by DMarinhoCodacy** [comment]
Hello @Kakadus ,

Thanks for your report.

We're bumping our tool to work with Python 3.10. Next week will be in production.

Thanks.
