### ISSUE TITLE
[CY-3864] Adding a .prospector.yml file brings up import errors

### ISSUE THREAD

**Issue by calina-c** [codacy/codacy-prospector#57]
Hello, I have a huge problem with the prospector tool. I added a .prospector.yml file in my repository to disable D213 checks. However, adding the file brings up 131 new possible issues related to import errors.

I have two options:
- Running without a .prospector.yml and having all the D213 errors show up and confuse team members. Fixing D213 triggers the mutually exclusive D212.
- Running with .prospector.yml and spewing up 131 import errors.

Why doesn't prospector run properly? Is it an older version?

**Comment by calina-c** [comment]
Related issues: https://github.com/codacy/codacy-meta/issues/442

There seem to be problems with imports while using a virtual environment, but that's mostly in IDEs, e.g.:
-  https://stackoverflow.com/questions/51095449/pylint-false-positive-e0401-import-errors-in-vscode-while-using-venv

**Comment by lolgab** [comment]
We already block all the `import` related issues in our direct PyLint wrapper.
It could be that we don't do it here, in the prospector tool.
I'm going to investigate that. What I suggest you as a workaround is to disable `pylint` from the Prospector configuration file and use Pylint inside `PyLint (Python 3)` Codacy tool, which is a better wrapper around PyLint than using it behind Prospector.

**Comment by lolgab** [comment]
Thank you very much for pointing it out @calina-c,
When we solved this problem on Pylint we forgot to port the solution to Prospector, and that's why you're experiencing this problem. I just open a PR that fixes this 😊.

**Comment by calina-c** [comment]
Thank you very much!

**Comment by calina-c** [comment]
@lolgab Except for the import errors, I can see adding .prospector.yml is introducing other issues, which were previously undetected from the default Codacy settings. I assume it is because the .prospector.yml completely overhauls the default Codacy rules, instead of supplementing them. Is there a baseline config I can use? E.g. the "default" .prospector.yml?

Ideally, I would like just to ignore a couple of issues, not add a stricter level of assessment.

**Comment by lolgab** [comment]
Can you share the `.prospector.yml` you're using?

**Comment by calina-c** [comment]
Actually I fond the trick. I looked at what codacy was disabling by default and added e.g.

```
pylint:
  run: false
```

For pylint, pyroma etc. (the unchecked boxes in the default config). It worked :)

Thank you for all your help, I appreciate it!

**Comment by lolgab** [comment]
No worries,
Happy to help :)
The fix for the import-error should be in production in the next hour.
